# Generated by Django 6.0.2 on 2026-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
