# Generated by Django 6.0.2 on 2026-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_address_job_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='job_logos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
