# Generated by Django 6.0.2 on 2026-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_deadline_job_experience_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
