# Generated by Django 6.0.2 on 2026-06-05 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Painter', 'Painter'), ('Mechanic', 'Mechanic'), ('Cleaner', 'Cleaner'), ('Driver', 'Driver'), ('Security', 'Security Guard'), ('Tutor', 'Tutor / Teacher'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('CA', 'CA / Accountant'), ('Designer', 'Graphic Designer'), ('Developer', 'Web / App Developer'), ('Photographer', 'Photographer'), ('Other', 'Other')], max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('timing', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Weekends', 'Weekends Only'), ('On-call', 'On Call'), ('By Appointment', 'By Appointment')], max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_photos/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
